"use client";

import { useQuery } from "@tanstack/react-query";
import { useState } from "react";
import { paperApi } from "@/lib/paperApi";
import { fmtPct } from "@/lib/format";
import { Link } from "react-router-dom";

type Phase22StrategySpec = {
  name: string;
  strategy_id: string;
  spec_name: string;
  description: string;
  symbol: string;
  timeframe: string;
  indicators: string[];
  entry_condition: string | null;
  allow_short: boolean;
  generated_by: string;
};

export function StrategiesWidget({ widget }: { widget: WidgetInstance }) {
  const { data: strategiesData, isLoading, error } = useQuery({
    queryKey: ["phase22-strategies"],
    queryFn: () => paperApi.getStrategies(),
    refetchInterval: 60_000,
    staleTime: 30_000,
  });

  const { data: regimeData } = useQuery({
    queryKey: ["market-regime"],
    queryFn: () => paperApi.getRegime({ symbol: "NSE:NIFTY50", timeframe: "1d" }),
    refetchInterval: 60_000,
  });

  const regime = regimeData?.data?.regime ?? "unknown";

  const strategies = strategiesData?.data ?? [];

  const getCategory = (name: string) => {
    if (name.includes("trend")) return "TREND_FOLLOWING";
    if (name.includes("moment")) return "MOMENTUM";
    if (name.includes("break")) return "BREAKOUT";
    if (name.includes("mean")) return "MEAN_REVERSION";
    if (name.includes("vol")) return "VOLATILITY";
    return "MULTI_STRATEGY";
  };

  return (
    <div className="h-full flex flex-col">
      <div className="flex items-center justify-between p-2 shrink-0 border-b border-[var(--border)]">
        <span className="font-mono text-[11px] text-[var(--text-dim)]">STRATEGIES</span>
        <span className="pill text-[10px]">
          {strategies.length} STRATEGIES
        </span>
      </div>

      <div className="flex-1 overflow-auto">
        {isLoading ? (
          <div className="p-4 text-center dim">Loading strategies…</div>
        ) : error ? (
          <div className="p-4 text-center down">Error: {(error as Error).message}</div>
        ) : strategies.length === 0 ? (
          <div className="p-4 text-center dim">No Phase 22 strategies registered</div>
        ) : (
          <table className="data-table w-full" style={{ fontSize: 11 }}>
            <thead className="sticky top-0 bg-[var(--bg-elev)]">
              <tr className="border-b border-[var(--border)] text-[9px] text-[var(--text-faint)]">
                <th className="p-1 text-left">Strategy</th>
                <th className="p-1 text-right">Category</th>
                <th className="p-1 text-left">Symbol</th>
                <th className="p-1 text-right">Timeframe</th>
                <th className="p-1 text-left">Indicators</th>
                <th className="p-1 text-right">Short</th>
                <th className="p-1 text-left">Generated By</th>
              </tr>
            </thead>
            <tbody>
              {strategies.map((s) => (
                <tr key={s.strategy_id} className="border-b border-[var(--border-soft)]">
                  <td className="p-1">
                    <Link to={`/paper/strategies/${s.name}`} className="td-id truncate block max-w-[160px]">
                      {s.spec_name}
                    </Link>
                  </td>
                  <td className="p-1 text-right">
                    <span className="pill text-[9px]">{getCategory(s.name)}</span>
                  </td>
                  <td className="p-1 text-left font-mono text-[10px]">{s.symbol}</td>
                  <td className="p-1 text-right font-mono text-[10px]">{s.timeframe}</td>
                  <td className="p-1 text-left truncate max-w-[180px] text-[10px] dim">
                    {s.indicators?.join(", ") || "—"}
                  </td>
                  <td className="p-1 text-right font-mono text-[10px]">{s.allow_short ? "YES" : "NO"}</td>
                  <td className="p-1 text-left font-mono text-[10px]">{s.generated_by}</td>
                </tr>
              ))}
            </tbody>
          </table>
        )}
      </div>

      <div className="p-1 border-t border-[var(--border)] dim text-[10px] text-center shrink-0">
        Regime: {regime} · Click strategy for details
      </div>
    </div>
  );
}