import { useEffect, useState, useCallback } from "react";
import { useParams, Link } from "react-router-dom";
import { paperApi } from "@/lib/paperApi";
import type { DeploymentListResponse, DashboardSnapshotResponse, EvidenceResponse } from "@/types/paper-api";
import { Panel, EmptyState, Button, StatusIndicator, MetricItem } from "@/components/ui";
import { EvidenceTimeline } from "@/components/paper/paperShared";

export function PaperStrategies() {
  const { strategyId } = useParams<{ strategyId: string }>();
  const [deployments, setDeployments] = useState<DeploymentListResponse | null>(null);
  const [strategy, setStrategy] = useState<DashboardSnapshotResponse["strategy"]>(null);
  const [evidence, setEvidence] = useState<EvidenceResponse | null>(null);
  const [loading, setLoading] = useState(false);
  const [error, setError] = useState<string | null>(null);

  const fetchAll = useCallback(async () => {
    if (!strategyId) return;
    setLoading(true);
    setError(null);
    setDeployments(null);
    setStrategy(null);
    setEvidence(null);

    const depRes = await paperApi.listDeployments({ strategy_id: strategyId, limit: 50 });
    if (!depRes.ok) {
      setError(depRes.error.message);
      setLoading(false);
      return;
    }

    setDeployments(depRes.data);

    if (depRes.data.deployments.length > 0) {
      const firstId = depRes.data.deployments[0].deployment_id;
      const [dashRes, evRes] = await Promise.all([
        paperApi.getDashboard(firstId).catch(() => null),
        paperApi.getEvidence(firstId).catch(() => null),
      ]);
      if (dashRes && dashRes.ok) {
        setStrategy(dashRes.data.strategy);
      }
      if (evRes && evRes.ok) {
        setEvidence(evRes.data);
      }
    }

    setLoading(false);
  }, [strategyId]);

  useEffect(() => {
    fetchAll();
  }, [fetchAll]);

  if (!strategyId) {
    return (
      <div className="paper-shell">
        <div className="pt-section"><h2>Select Strategy</h2></div>
        <EmptyState title="No strategy selected" hint="Navigate to a strategy from the Deployments page." />
      </div>
    );
  }

  const hasDeployments = deployments && deployments.deployments.length > 0;

  return (
    <div className="paper-shell">
      <div className="pt-section">
        <Link to="/paper/deployments" className="section-sub">← Paper Deployments</Link>
      </div>

      {loading && <StrategySkeleton />}

      {error && !loading && (
        <div className="error-state" role="alert">
          <div className="es-icon" aria-hidden="true">!</div>
          <div className="es-title">Unable to load strategy</div>
          <div className="es-hint">{error}</div>
          <Button variant="secondary" size="sm" onClick={fetchAll}>Retry</Button>
        </div>
      )}

      {!loading && !error && (
        <>
          {strategy ? (
            <>
              {/* Strategy Header */}
              <div className="detail-head">
                <div className="dh-top">
                  <div>
                    <div className="dh-title">{strategy.name || strategyId}</div>
                    <div className="dh-sub">{strategy.strategy_id} · {strategy.symbol} · {strategy.timeframe}</div>
                  </div>
                  <div className="row gap-sm wrap">
                    <span className="pill">PAPER</span>
                    <StatusIndicator status={strategy.lifecycle_status} />
                  </div>
                </div>
                <div className="dh-metrics">
                  <div className="dh-metric">
                    <span className="m-label">Lifecycle</span>
                    <span className="m-value">{strategy.lifecycle_status}</span>
                  </div>
                  <div className="dh-metric">
                    <span className="m-label">Generated By</span>
                    <span className="m-value">{strategy.generated_by}</span>
                  </div>
                  <div className="dh-metric">
                    <span className="m-label">Deployments</span>
                    <span className="m-value">{deployments?.count ?? 0}</span>
                  </div>
                  <div className="dh-metric">
                    <span className="m-label">Spec Hash</span>
                    <span className="m-value" style={{ fontFamily: "var(--mono)", fontSize: 12 }}>{strategy.spec_hash.slice(0, 12)}…</span>
                  </div>
                </div>
              </div>

              {/* Evidence Progression */}
              <Panel title="Evidence Progression">
                {evidence ? (
                  <>
                    <EvidenceTimeline
                      researchCount={evidence.evidence.research_count}
                      walkForwardCount={evidence.evidence.walk_forward_count}
                      paperCount={evidence.evidence.paper_trading_count}
                    />
                    <div className="metric-grid">
                      <MetricItem label="Latest Research" value={evidence.evidence.latest_research_at ? new Date(evidence.evidence.latest_research_at).toLocaleString() : "—"} />
                      <MetricItem label="Latest Walk Forward" value={evidence.evidence.latest_walk_forward_at ? new Date(evidence.evidence.latest_walk_forward_at).toLocaleString() : "—"} />
                      <MetricItem label="Latest Paper Trading" value={evidence.evidence.latest_paper_trading_at ? new Date(evidence.evidence.latest_paper_trading_at).toLocaleString() : "—"} />
                    </div>
                  </>
                ) : (
                  <EmptyState title="No evidence recorded" hint="Evidence will appear as the strategy progresses through research phases." />
                )}
              </Panel>
            </>
          ) : hasDeployments ? (
            <Panel subtle>
              <EmptyState title="Strategy metadata unavailable" hint="Could not load strategy details from the backend. Deployments are shown below." />
            </Panel>
          ) : (
            <Panel subtle>
              <EmptyState title="No strategy data" hint={`Strategy ${strategyId} has no deployments and no recorded evidence.`} />
            </Panel>
          )}

          {/* Deployments */}
          <div>
            <div className="pt-section">
              <h2>Deployments</h2>
              <span className="section-sub">{deployments?.count ?? 0} total</span>
            </div>
            {hasDeployments ? (
              <Panel subtle>
                <table className="data dense">
                  <thead>
                    <tr>
                      <th>Deployment</th>
                      <th>Symbol</th>
                      <th>Timeframe</th>
                      <th>Status</th>
                      <th>Created</th>
                    </tr>
                  </thead>
                  <tbody>
                    {deployments.deployments.map((d) => (
                      <tr key={d.deployment_id}>
                        <td><Link to={`/paper/deployments/${d.deployment_id}`} className="td-id">{d.deployment_id}</Link></td>
                        <td>{d.symbol}</td>
                        <td>{d.timeframe}</td>
                        <td><StatusIndicator status={d.status} /></td>
                        <td className="td-muted">{d.created_at?.slice(0, 10) ?? "—"}</td>
                      </tr>
                    ))}
                  </tbody>
                </table>
              </Panel>
            ) : (
              <Panel subtle>
                <EmptyState title="No deployments" hint={`No deployments found for strategy ${strategyId}.`} />
              </Panel>
            )}
          </div>
        </>
      )}
    </div>
  );
}

function StrategySkeleton() {
  return (
    <div className="stack gap-lg" aria-label="Loading strategy detail">
      <div className="skel skel-block" style={{ height: 100 }} />
      <div className="skel skel-block" style={{ height: 80 }} />
      <div className="skel skel-block" style={{ height: 180 }} />
      <div className="skel skel-block" style={{ height: 160 }} />
    </div>
  );
}
