import { useEffect, useState, useCallback } from "react";
import { useParams, Link } from "react-router-dom";
import { paperApi } from "@/lib/paperApi";
import type {
  AllocationResponse,
  DeploymentListResponse,
  DashboardSnapshotResponse,
  EvidenceResponse,
  Phase22StrategySpec,
  RegimeResponse,
} from "@/types/paper-api";
import { Panel, EmptyState, Button, StatusIndicator, MetricItem, Loading } from "@/components/ui";
import { EvidenceTimeline } from "@/components/paper/paperShared";

export function PaperStrategies() {
  const { strategyId } = useParams<{ strategyId: string }>();
  const [deployments, setDeployments] = useState<DeploymentListResponse | null>(null);
  const [strategy, setStrategy] = useState<DashboardSnapshotResponse["strategy"]>(null);
  const [evidence, setEvidence] = useState<EvidenceResponse | null>(null);
  const [loading, setLoading] = useState(false);
  const [error, setError] = useState<string | null>(null);

  const fetchAll = useCallback(async () => {
    if (!strategyId) return;
    setLoading(true);
    setError(null);
    setDeployments(null);
    setStrategy(null);
    setEvidence(null);

    const depRes = await paperApi.listDeployments({ strategy_id: strategyId, limit: 50 });
    if (!depRes.ok) {
      setError(depRes.error.message);
      setLoading(false);
      return;
    }

    setDeployments(depRes.data);

    if (depRes.data.deployments.length > 0) {
      const firstId = depRes.data.deployments[0].deployment_id;
      const [dashRes, evRes] = await Promise.all([
        paperApi.getDashboard(firstId).catch(() => null),
        paperApi.getEvidence(firstId).catch(() => null),
      ]);
      if (dashRes && dashRes.ok) {
        setStrategy(dashRes.data.strategy);
      }
      if (evRes && evRes.ok) {
        setEvidence(evRes.data);
      }
    }

    setLoading(false);
  }, [strategyId]);

  useEffect(() => {
    fetchAll();
  }, [fetchAll]);

  if (!strategyId) {
    return <StrategyLeaderboard />;
  }

  const hasDeployments = deployments && deployments.deployments.length > 0;

  return (
    <div className="paper-shell">
      <div className="pt-section">
        <Link to="/paper/deployments" className="section-sub">← Paper Deployments</Link>
      </div>

      {loading && <StrategySkeleton />}

      {error && !loading && (
        <div className="error-state" role="alert">
          <div className="es-icon" aria-hidden="true">!</div>
          <div className="es-title">Unable to load strategy</div>
          <div className="es-hint">{error}</div>
          <Button variant="secondary" size="sm" onClick={fetchAll}>Retry</Button>
        </div>
      )}

      {!loading && !error && (
        <>
          {strategy ? (
            <>
              {/* Strategy Header */}
              <div className="detail-head">
                <div className="dh-top">
                  <div>
                    <div className="dh-title">{strategy.name || strategyId}</div>
                    <div className="dh-sub">{strategy.strategy_id} · {strategy.symbol} · {strategy.timeframe}</div>
                  </div>
                  <div className="row gap_sm wrap">
                    <span className="pill">PAPER</span>
                    <StatusIndicator status={strategy.lifecycle_status} />
                  </div>
                </div>
                <div className="dh-metrics">
                  <div className="dh-metric">
                    <span className="m-label">Lifecycle</span>
                    <span className="m-value">{strategy.lifecycle_status}</span>
                  </div>
                  <div className="dh-metric">
                    <span className="m-label">Generated By</span>
                    <span className="m-value">{strategy.generated_by}</span>
                  </div>
                  <div className="dh-metric">
                    <span className="m-label">Deployments</span>
                    <span className="m-value">{deployments?.count ?? 0}</span>
                  </div>
                  <div className="dh-metric">
                    <span className="m-label">Spec Hash</span>
                    <span className="m-value" style={{ fontFamily: "var(--mono)", fontSize: 12 }}>{strategy.spec_hash.slice(0, 12)}…</span>
                  </div>
                </div>
              </div>

              {/* Evidence Progression */}
              <Panel title="Evidence Progression">
                {evidence ? (
                  <>
                    <EvidenceTimeline
                      researchCount={evidence.evidence.research_count}
                      walkForwardCount={evidence.evidence.walk_forward_count}
                      paperCount={evidence.evidence.paper_trading_count}
                    />
                    <div className="metric-grid">
                      <MetricItem label="Latest Research" value={evidence.evidence.latest_research_at ? new Date(evidence.evidence.latest_research_at).toLocaleString() : "—"} />
                      <MetricItem label="Latest Walk Forward" value={evidence.evidence.latest_walk_forward_at ? new Date(evidence.evidence.latest_walk_forward_at).toLocaleString() : "—"} />
                      <MetricItem label="Latest Paper Trading" value={evidence.evidence.latest_paper_trading_at ? new Date(evidence.evidence.latest_paper_trading_at).toLocaleString() : "—"} />
                    </div>
                  </>
                ) : (
                  <EmptyState title="No evidence recorded" hint="Evidence will appear as the strategy progresses through research phases." />
                )}
              </Panel>
            </>
          ) : hasDeployments ? (
            <Panel subtle>
              <EmptyState title="Strategy metadata unavailable" hint="Could not load strategy details from the backend. Deployments are shown below." />
            </Panel>
          ) : (
            <Panel subtle>
              <EmptyState title="No strategy data" hint={`Strategy ${strategyId} has no deployments and no recorded evidence.`} />
            </Panel>
          )}

          {/* Deployments */}
          <div>
            <div className="pt-section">
              <h2>Deployments</h2>
              <span className="section-sub">{deployments?.count ?? 0} total</span>
            </div>
            {hasDeployments ? (
              <Panel subtle>
                <table className="data dense">
                  <thead>
                    <tr>
                      <th>Deployment</th>
                      <th>Symbol</th>
                      <th>Timeframe</th>
                      <th>Status</th>
                      <th>Created</th>
                    </tr>
                  </thead>
                  <tbody>
                    {deployments.deployments.map((d) => (
                      <tr key={d.deployment_id}>
                        <td><Link to={`/paper/deployments/${d.deployment_id}`} className="td-id">{d.deployment_id}</Link></td>
                        <td>{d.symbol}</td>
                        <td>{d.timeframe}</td>
                        <td><StatusIndicator status={d.status} /></td>
                        <td className="td-muted">{d.created_at?.slice(0, 10) ?? "—"}</td>
                      </tr>
                    ))}
                  </tbody>
                </table>
              </Panel>
            ) : (
              <Panel subtle>
                <EmptyState title="No deployments" hint={`No deployments found for strategy ${strategyId}.`} />
              </Panel>
            )}
          </div>
        </>
      )}
    </div>
  );
}

// --------------------------------------------------------------------------- #
// Phase 22 — Strategy Leaderboard (shown when no strategyId is selected)
// --------------------------------------------------------------------------- #
function StrategyLeaderboard() {
  const [strategies, setStrategies] = useState<Phase22StrategySpec[] | null>(null);
  const [regime, setRegime] = useState<RegimeResponse | null>(null);
  const [allocation, setAllocation] = useState<AllocationResponse | null>(null);
  const [strategiesLoading, setStrategiesLoading] = useState(true);
  const [regimeLoading, setRegimeLoading] = useState(true);
  const [allocationLoading, setAllocationLoading] = useState(true);
  const [strategiesError, setStrategiesError] = useState<string | null>(null);
  const [regimeError, setRegimeError] = useState<string | null>(null);
  const [allocationError, setAllocationError] = useState<string | null>(null);

  const fetchStrategies = useCallback(async () => {
    setStrategiesLoading(true);
    setStrategiesError(null);
    setStrategies(null);
    const res = await paperApi.getStrategies();
    if (res.ok) {
      setStrategies(res.data);
    } else {
      setStrategiesError(res.error.message);
    }
    setStrategiesLoading(false);
  }, []);

  const fetchRegime = useCallback(async () => {
    setRegimeLoading(true);
    setRegimeError(null);
    setRegime(null);
    const res = await paperApi.getRegime();
    if (res.ok) {
      setRegime(res.data);
    } else {
      setRegimeError(res.error.message);
    }
    setRegimeLoading(false);
  }, []);

  const fetchAllocation = useCallback(async () => {
    setAllocationLoading(true);
    setAllocationError(null);
    setAllocation(null);
    const res = await paperApi.getAllocation();
    if (res.ok) {
      setAllocation(res.data);
    } else {
      setAllocationError(res.error.message);
    }
    setAllocationLoading(false);
  }, []);

  useEffect(() => {
    fetchStrategies();
    fetchRegime();
    fetchAllocation();
  }, [fetchStrategies, fetchRegime, fetchAllocation]);

  const refresh = () => {
    fetchStrategies();
    fetchRegime();
    fetchAllocation();
  };

  return (
    <div className="paper-shell">
      <div className="pt-section">
        <h1>Strategy Intelligence</h1>
        <span className="section-sub">Phase 22 — Adaptive Multi-Strategy Market Intelligence</span>
      </div>

      {/* Current Market Regime */}
      <Panel title="Current Market Regime">
        {regimeLoading ? (
          <Loading label="Loading market regime..." />
        ) : regimeError ? (
          <div className="es-hint muted">
            Market regime unavailable — no market data provider configured for the dev server.
            <br />
            <span className="detail-error">{regimeError}</span>
          </div>
        ) : regime ? (
          <div className="metric-grid">
            <MetricItem label="Regime" value={regime.regime} />
            <MetricItem label="Confidence" value={`${Math.round(regime.confidence * 100)}%`} />
            <MetricItem label="At" value={new Date(regime.regime_at_ms).toLocaleString()} />
          </div>
        ) : null}
      </Panel>

      {/* Recommended Strategy Allocation */}
      <Panel title="Strategy Allocation" className="mt_md">
        {allocationLoading ? (
          <Loading label="Loading strategy allocation..." />
        ) : allocationError ? (
          <div className="es-hint muted">
            Strategy allocation unavailable — no market data provider configured.
            <br />
            <span className="detail-error">{allocationError}</span>
          </div>
        ) : allocation ? (
          <>
            <div className="metric-grid">
              <MetricItem label="Strategies Available" value={allocation.total_strategies_available} />
              <MetricItem label="Regime Fit" value={`${Math.round(allocation.regime_fit * 100)}%`} />
            </div>
            <div className="mt_sm">
              <h3>Recommended Allocation</h3>
              <table className="data dense">
                <thead>
                  <tr>
                    <th>#</th>
                    <th>Strategy</th>
                    <th>Category</th>
                    <th>Weight</th>
                    <th>Regime Fit</th>
                    <th>Research Score</th>
                  </tr>
                </thead>
                <tbody>
                  {allocation.selected_strategies.map((sw, i) => (
                    <tr key={sw.strategy_name}>
                      <td>{i + 1}</td>
                      <td>
                        <Link to={`/paper/strategies/${sw.strategy_name}`} className="td-id">
                          {sw.strategy_name}
                        </Link>
                      </td>
                      <td><span className="pill">{sw.category}</span></td>
                      <td>{Math.round(sw.weight * 100)}%</td>
                      <td>{Math.round(sw.regime_compatibility * 100)}%</td>
                      <td>{sw.research_score !== null ? Math.round(sw.research_score * 100) : "—"}</td>
                    </tr>
                  ))}
                </tbody>
              </table>
            </div>
          </>
        ) : null}
      </Panel>

      {/* Strategy Leaderboard */}
      <Panel title="Strategy Leaderboard" className="mt_md">
        {strategiesLoading ? (
          <Loading label="Loading strategies..." />
        ) : strategiesError ? (
          <div className="error-state" role="alert">
            <div className="es-icon" aria-hidden="true">!</div>
            <div className="es-title">Unable to load strategies</div>
            <div className="es-hint">{strategiesError}</div>
            <Button variant="secondary" size="sm" onClick={refresh}>Retry</Button>
          </div>
        ) : strategies && strategies.length > 0 ? (
          <table className="data dense">
            <thead>
              <tr>
                <th>Strategy</th>
                <th>Category</th>
                <th>Symbol</th>
                <th>Timeframe</th>
                <th>Indicators</th>
                <th>Entry</th>
                <th>Short</th>
                <th>Created By</th>
              </tr>
            </thead>
            <tbody>
              {strategies.map((s) => (
                <tr key={s.strategy_id}>
                  <td>
                    <Link to={`/paper/strategies/${s.name}`} className="td-id">{s.spec_name}</Link>
                  </td>
                  <td>
                    {s.name.includes("trend") ? "TREND_FOLLOWING" : s.name.includes("moment") ? "MOMENTUM" : s.name.includes("break") ? "BREAKOUT" : "MEAN_REVERSION"}
                  </td>
                  <td>{s.symbol}</td>
                  <td>{s.timeframe}</td>
                  <td>{s.indicators?.join(", ")}</td>
                  <td>{s.entry_condition ?? "—"}</td>
                  <td>{s.allow_short ? "Yes" : "No"}</td>
                  <td><span className="pill">{s.generated_by}</span></td>
                </tr>
              ))}
            </tbody>
          </table>
        ) : (
          <EmptyState
            title="No strategies available"
            hint="No Phase 22 strategies are registered."
          />
        )}
      </Panel>

      <div className="pt-section">
        <span className="section-sub">DEMO / SIMULATED — No live market data required.</span>
      </div>
    </div>
  );
}

function StrategySkeleton() {
  return (
    <div className="stack gap_lg" aria-label="Loading strategy detail">
      <div className="skel skel-block" style={{ height: 100 }} />
      <div className="skel skel-block" style={{ height: 80 }} />
      <div className="skel skel-block" style={{ height: 180 }} />
      <div className="skel skel-block" style={{ height: 160 }} />
    </div>
  );
}
